### ISSUE TITLE
Check farming characters potion number

### ISSUE THREAD

**Issue by Ciechom** [johnnyawesome/Adventure.Land#5]
Hello, I don't know if it's possible or not but adding some logic to check fighting characters inventory for potions to not overstock them or to get only missing potions up to some limit would be nice. I haven't paid attention for a while to my fighters and when I logged into them after several days all of them have multiple stacks of over 9000 of smaller potions.

**Comment by johnnyawesome** [comment]
You can adjust this in the code, inside the "merchantSkills"-Module:

//Number of potions to buy each round. 
//Gets tripled if the hunted monster requires a master
const potions = {
	hpot0: 6,
	hpot1: 30,
	mpot0: 20,
	mpot1: 60
};

Set these numbers to lower values, and the merchant will bring less potions.

If you have a computer (endgame) characters can buy their own potions from anywhere.

I am not there yet, and this is the best I have. ;)

But if you set the numbers I mentioned above inside the "merchantSkills"-Module lower, you should be fine.

Also: I fixed a bunch of bugs today anyways, please get the latest version of the code.
(There were a few crashes that caused disconnects of the merchant (and therefor all characters). You should get the newest version of the code - it is fixed there.)
