### ISSUE TITLE
Add secondary farming target

### ISSUE THREAD

**Issue by Ciechom** [johnnyawesome/Adventure.Land#6]
I noticed that when I set the script to farm snakes it also kills orange snakes but not the other way around. So if I would like to prioritize killing orange snakes by setting farming to them my party just stands in one spot killing only orange snakes. Maybe I'm missing something how to do it properly to kill osnakes first and if there are none to kill regular snakes.

**Comment by johnnyawesome** [comment]
The script hunts what you tell it to.

Orange snakes are rare.

If there is no orange snake around, it will start going after "normal" snakes.

This is so that you don't "waste time" waiting for rare monsters, and always farm "something".

I fixed a bunch of bugs today anyways, please get the latest version of the code.
(There were a few crashes that caused disconnects of the merchant (and therefor all characters). You should get the newest version of the code - it is fixed there.)

**Comment by Ciechom** [comment]
I don't know how it works after update yet.

Before update whenever I got quest for osnakes my party was only killing them and didn't target regular snakes, so most of the time they were standing and waiting for respawn.

**Comment by johnnyawesome** [comment]
Just pull the newest version of the code, I fixed a bunch of things (Disconnexts / Crashes) today.

Hopefully it works then. Please let me know.

**Comment by Ciechom** [comment]
Just after posting my comment I got quest for osnakes, after killing all in range my party just stands around waiting for more to spawn. They are not targeting regular snakes then.

**Comment by johnnyawesome** [comment]
Oh, okay. That's weird. What Server are you on?

**Comment by Ciechom** [comment]
EU I, my party is: Ciechom, Yanush and Healr.

**Comment by johnnyawesome** [comment]
Yes, let me see pls. Let's meet at osnakes. It's weird because for me, it works.

**Comment by Ciechom** [comment]
When it's another way around when I get a quest or set them to kill regular snakes, when they run out of targets then they target orange snakes.

**Comment by johnnyawesome** [comment]
That's as it should be. So they don't "wait".

Is your merch "Seler"?

**Comment by Ciechom** [comment]
I know that's why I'm surprised that it doesn't work when the main target is osnakes.

Yeah Seler is my merchant.

Right now it's: bat, mini mush, rat.

**Comment by johnnyawesome** [comment]
I found another typo (sorry) Pls update again.

Pls let me know if it works afterwards.

I have an additional function (not yet public, because not thoroughly tested) I could give you.
It does what you ask, but it's new (not yet proven stable).

Please update first and let me know if it helped.

**Comment by Ciechom** [comment]
After latest update they still only attack osnakes.

Maybe I'm dumb and I'm importing the code wrong? What's the best way to import the code ingame?

I'm always happy to test new things but unfortunately I'm leaving tommorow for 4-5 days so I won't be able to attend the bots.
